spring:
  datasource:
    url: ${JDBC_URL:jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASS:''}
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
